glolab/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
from django.views.generic import TemplateView
from userpro import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^student/$',views.allstudents, name='register'),
    url(r'^student/register/$',views.register, name='register'),
    url(r'^student/editprofile/$', views.editstudentprofile, name='editstudentprofile'),
    url(r'^student/edit/$',views.editprofile,name='edit'),
    url(r'^company/register/$',views.companyregister,name='companyregister'),
    url(r'^company/edit/$',views.editcompanyprofile,name='companyedit'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^projects/', include('projects.urls')),
    (r'^accounts/',include('registration.backends.simple.urls')),
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

userpro/urls.py
from django.conf.urls import patterns, url
from userpro import views

urlpatterns = patterns('',
	url(r'^register/$', views.register, name='register'),
	
	)

userpro/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project
# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User,null=True)
	picture = models.ImageField(upload_to='project_image',blank = True)
	project_a = models.ForeignKey(Project,default='')
	about_me = models.TextField(max_length=450, default='', blank=True)
	
	def __unicode__(self):
		return self.user.username

class CompanyProfile(models.Model):
	user = models.OneToOneField(User)
	company_name=models.CharField(max_length=128)
	project_a = models.ForeignKey(Project,default='')
	description = models.TextField(max_length=100, default='', blank=True)
	website= models.URLField(blank=True)

	def __unicode__(self):
		return self.company_name

userpro/forms.py
from django import forms
from django.contrib.auth.models import User
from userpro.models import UserProfile,CompanyProfile
from django.utils.translation import ugettext, ugettext_lazy as _

class UserForm(forms.ModelForm):
	error_messages = {
		'password_mismatch': _("The two password fields didn't match."),
	}
	password1 = forms.CharField(label=_("Password"),
		widget=forms.PasswordInput)
	password2 = forms.CharField(label=_("Password confirmation"),
		widget=forms.PasswordInput,
		help_text=_("Enter the same password as above, for verification."))

	class Meta:
		model = User
		fields = ("username",)

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError(
				self.error_messages['password_mismatch'],
				code='password_mismatch',
			)
		return password2

	def save(self, commit=True):
		user = super(UserForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		if commit:
			user.save()
		return user
	class Meta:
		model = User
		fields = ('username', 'email','first_name','last_name', )

class UserProfileForm(forms.ModelForm):
	about_me = forms.CharField(required=True)
	picture = forms.ImageField(required=False, help_text='profile picture')
	project_a = forms.SlugField(required=False, widget = forms.HiddenInput())
	project_b = forms.SlugField(required=False, widget = forms.HiddenInput())

	class Meta:
		model = UserProfile
		fields=('about_me','picture')

class ApplyProjectForm(forms.ModelForm):
	about_me = forms.CharField(required=False)
	picture = forms.ImageField(required=False)
	project_a = forms.SlugField(required=False, widget = forms.HiddenInput())
	project_b = forms.SlugField(required=False, widget = forms.HiddenInput())

	class Meta:
		model = UserProfile
		fields=('about_me','picture')


class editStudentProfile(forms.ModelForm):
	username = forms.CharField(required=True)
	email = forms.EmailField(required=True)
	first_name = forms.CharField(required=False)
	last_name = forms.CharField(required=False)

	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name',)

	def clean_email(self):
		username = self.cleaned_data.get('username')
		email = self.cleaned_data.get('email')
		if email and User.objects.filter(email=email).exclude(username=username).count():
			raise forms.ValidationError('This email address is already in use. Please give another email address.')
		return email

	def save(self, commit=True):
		user = super(editStudentProfile, self).save(commit=False)
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class editStudentDetailProfile(forms.ModelForm):
	about_me = forms.CharField(required=False)
	picture = forms.ImageField(required=False,help_text='profile picture')
	project_a = forms.SlugField(required=False, widget = forms.HiddenInput())
	project_b = forms.SlugField(required=False, widget = forms.HiddenInput())

	class Meta:
		model = UserProfile
		fields = ('about_me','picture')

	def save(self, commit=True):
		user = super(editStudentDetailProfile, self).save(commit=False)
		if commit:
			user.save()
		return user


class CompanyProfileForm(forms.ModelForm):
	company_name = forms.CharField(max_length=128, required=True)
	description = forms.CharField(label='', 
					widget=forms.Textarea(attrs={'placeholder': 'description','class':"form-control"}))
	class Meta:
		model = CompanyProfile
		fields=('company_name','description','website')

userpro/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from userpro.models import UserProfile, CompanyProfile
from userpro.forms import UserProfileForm, UserForm,CompanyProfileForm,editStudentProfile,editStudentDetailProfile
from django.http import HttpResponseRedirect
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required, user_passes_test
# Create your views here.


def register(request):
	registered = False
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST, request.FILES)

		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()
			
			user = user_form.save(commit=False)
			
			user.save()
			g=Group.objects.get(name="student")
			g.user_set.add(user)
			
			profile = profile_form.save(commit=False)
			profile.user = user

			profile.save()

			registered = True
			return HttpResponseRedirect('/')

		else:
			print user_form.errors, profile_form.errors
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request,
		'userpro/register.html',
		{'user_form': user_form, 'profile_form': profile_form, 'registered':registered})


@login_required()
def editstudentprofile(request):
	if request.method == 'POST':
		form = editStudentProfile(request.POST, instance = request.user)
		detail = UserProfileForm(request.POST, instance = request.user)
		if form.is_valid() and detail.is_valid():
			user = form.save()
			user.save()
			profile = detail.save(commit=False)
			profile.user=user
			profile.save()
			return HttpResponseRedirect("/")
		else:
			print form.errors() and profile_form.errors()
	else:
		form = editStudentProfile()
		detail = UserProfileForm()
	
	return render(request, 'registration/student_profile_edit.html', {'form':form,'' 'detail': detail})


def companyregister(request):
	registered =False
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = CompanyProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()
			user.set_password(user.password)
			user.save()
			g=Group.objects.get(name="company")
			g.user_set.add(user)
			profile = profile_form.save(commit=False)
			profile.user = user

			profile.save()

			registered = True

		else:
			print user_form.errors, profile_form.errors
	else:
		user_form = UserForm()
		profile_form = CompanyProfileForm()

	return render(request,
		'userpro/companyregister.html',
		{'user_form': user_form, 'profile_form': profile_form, 'registered':registered})


def is_student(user):
	return user.groups.filter(name='student').exists()

@user_passes_test(is_student, login_url='/')
def editprofile(request):
	edit = False
	try:
		user_obj = User.Objects.get(user=request.user)
	except:
		user_obj = None
	if request.method == 'POST':
		profile_form = UserProfileForm(request.POST,request.FILES, instance = request.user.userprofile)
		user = request.user
		if profile_form.is_valid():

			profile = profile_form.save(commit=False)
			profile.user=request.user
			profile.save()
			edit = True
			return HttpResponseRedirect('/')

		else:
			print profile_form.errors
	else:
		profile_form=UserProfileForm()
	return render(request,
		'userpro/useredit.html',
		{'profile_form':profile_form})

def is_company(user):
	return user.groups.filter(name='company').exists()

@user_passes_test(is_company,login_url='/')
def editcompanyprofile(request):
	try:
		company_obj=User.objects.get(user=request.user)
	except:
		company_obj=None
	if request.method=="POST":
		profile_form = CompanyProfileForm(data=request.POST, instance = request.user.companyprofile)
		user = request.user
		if profile_form.is_valid():

			profile = profile_form.save(commit=False)
			profile.user=request.user
			
			profile.save()
			edit = True
			return HttpResponseRedirect('/')

		else:
			print profile_form.errors
	else:
		profile_form=CompanyProfileForm()
	return render(request,
		'userpro/companyedit.html',
		{'profile_form':profile_form})
@login_required()
def editstudentprofile(request):
	if request.method == 'POST':
		form = editStudentProfile(request.POST, instance = request.user)
		profile_form = UserProfileForm(data=request.POST, instance = request.user)
		if form.is_valid() and profile_form.is_valid():
			form.save()
			profile = profile_form.save(commit=False)
			
			profile.save()
			return HttpResponseRedirect("/")
		else:
			print form.errors() and profile_form.errors()
	else:
		form = editStudentProfile()
		detail = UserProfileForm()
	
	return render(request, 'registration/student_profile_edit.html', {'form':form, 'detail': detail})


def index(request):
	
	# Construct a dictionary to pass to the template engine as its context.
	# Note the key boldmessage is the same as {{ boldmessage }} in the template!
	

	# Return a rendered response to send to the client.
	# We make use of the shortcut function to make our lives easier.
	# Note that the first parameter is the template we wish to use.
	return render(request, 'student.html', {})


@login_required
def profile(request):
	user=request.user
	return render(request,'userpro/profile.html',{'user':user})

def allstudents(request):
	users = User.objects.order_by('username')
	students = []
	for user in users:
		if user.groups.filter(name='student').exists():	
			students.append(user)
	num = len(students)
	column = num%3
	return render(request, 'userpro/all_student_view.html', {'students':students, 'num':num,'column':column})

templates/userpro/all_student_view.html
{% extends "base.html" %}


{% block content%}



 <section  id="students">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                
                    <h2>Students </h2>
              

                
                </div>
            </div>
<div class="row">
{% for student in students %}


   <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
      	{% if student.userprofile.picture %}
         <img src="{{student.userprofile.picture}}" alt="profile picture">
         {% else %}
         <img src="http://freelanceme.net/Images/default%20profile%20picture.png" alt="profile picture">
         {% endif %}
      </div>
      <div class="caption">
         <h3>{{student.username}}</h3>
         <p>{{ student.userprofile.about_me}}</p>
      </div>
   </div>


{% endfor %}

</div>

</section>

{%endblock%}

templates/userpro/companyedit.html
{% extends "base.html" %}


{% block content%}


{% if edit %}
		<section>
		<div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Edit Complete</h2>
                    <br>
                    <a href="/"> Return to Home</a>
                </div>
            </div>
		
		</section>
		{% else %}
<div class ="container" style="padding-top:70px">
	<div class="row">
		<div class="col-lg-12 text-center">
			<h2 class="form-signin-heading">Edit Here</h2>
		</div>
	</div>
</div>
<hr/>
<div class="row container">
<div class="col-lg-8 col-lg-offset-2">
<form id="user_form" method = "post" action="/company/edit/" enctype="multipart/form-data">
{% csrf_token %}
<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls"><label for="id_company_name">Company name:</label><input class="form-control" id="id_company_name" maxlength="128" name="company_name" type="text" placeholder="Enter Company Name"  /><br />
	</div>
</div>


<div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
	<textarea class="form-control" cols="40" id="id_description" name="description" placeholder="Description" required="false" rows="10">
</textarea>
	</div>
</div>
<br/>
<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls">
	<label for="id_website">Website:</label><input class="form-control" id="id_website" maxlength="128" name="website" type="text" placeholder="Enter Website"  />
	</div>
</div>
<br>

<div class="row">
	<div class="form-group col-xs-12">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
</div>


		</form>
	</div>
</div>
{{profile_form.errors}}
{%endif%}
{%endblock%}

templates/userpro/companyregister.html
{% extends "base.html" %}


{% block content%}


{% if registered %}
		<section>
		<div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Registration Complete</h2>
                    <br>
                    <a href="/"> Return to Home</a>
                </div>
            </div>
		
		</section>
		{% else %}
<div class ="container" style="padding-top:70px">
	<div class="row">
		<div class="col-lg-12 text-center">
			<h2 class="form-signin-heading">Sign Up Here</h2>
		</div>
	</div>
</div>
<hr/>
<div class="row container">
<div class="col-lg-8 col-lg-offset-2">
<form id="user_form" method = "post" action="/company/register/" enctype="multipart/form-data">
{% csrf_token %}
<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls"> 
	<label for="id_username">Username:</label><input class="form-control" id="id_username" maxlength="30" name="username" type="text" placeholder="Enter Username" /><br />
	
	</div>
</div>

<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls"><label for="id_email">Email address:</label><input class="form-control" id="id_email" maxlength="75" name="email" type="email" placeholder="Enter Email" />
	</div>
</div>
<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls">
	<label for="id_password">Password:</label><input class="form-control" id="id_password" name="password" type="password" placeholder="Enter Password" />
	</div>
</div>

<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls">
	<label for="id_company_name">Company Name:</label><input class="form-control" id="id_company_name" maxlength="128" name="company_name" type="text" required="true" placeholder="Enter Company Name"  /><br />
	</div>
</div>

<div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
    <label>Description</label>
	<textarea class="form-control" id="id_description" name="description" placeholder="Description"rows="5">
	</textarea>
	</div>
</div>
<br>

<div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
    <label for="id_website">Website:</label><input class="form-control" id="id_website" maxlength="200" placeholder="Website"name="website" type="url" />
   	</div>
</div>

<br>

<div class="row">
	<div class="form-group col-xs-12">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
</div>


		</form>
	</div>
</div>
{%endif%}
{%endblock%}

templates/userpro/profile.html
{%extends "base.html"%}
{%block content%}
<section>
<div class="container">
            <div class="row">
           <div class="col-lg-12">
{%if user.userprofile %}
<br>
<br>
Firs Name: {{user.first_name}}
<br>
Last Name: {{user.last_name}}
<br>
About Me: {{user.userprofile.about_me}}
<br>
      <a href="/student/edit/" class="btn btn btn-primary">Edit Profile</a>
{%elif user.companyprofile %}
<br>
<br>
Company Name: {{user.companyprofile.company_name}}
<br>
Description: {{user.companyprofile.description}}
<br>
Website: <a href="{{user.companyprofile.website}} ">{{user.companyprofile.website}} </a>
<br>
 <a href="/company/edit/" class="btn btn btn-primary">Edit Company Profile</a>
{%endif%}
<a href="/accounts/password/change/" class="btn btn btn-primary">
                        Change Password
                    </a>
   
</div>
</div>
</div>
</section>


{%endblock%}

templates/userpro/register.html
{% extends "base.html" %}


{% block content%}


{% if registered %}
		<section>
		<div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Registration Complete</h2>
                    <br>
                    <a href="/"> Return to Home</a>
                </div>
            </div>
		
		</section>
		{% else %}
<div class ="container" style="padding-top:70px">
	<div class="row">
		<div class="col-lg-12 text-center">
			<h2 class="form-signin-heading">Sign Up Here</h2>
		</div>
	</div>
</div>
<hr/>
{{user_form.errors}}
<br>
<div class="row container">
<div class="col-lg-8 col-lg-offset-2">
<form id="user_form" method = "post" action="/student/register/" enctype="multipart/form-data">
{% csrf_token %}

<!--
<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls"> 
	<label for="id_username">Username:</label><input class="form-control" id="id_username" maxlength="30" name="username" type="text" placeholder="Enter Username" /><br />
	
	</div>
</div>

<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls"><label for="id_email">Email address:</label><input class="form-control" id="id_email" maxlength="75" name="email" type="email" placeholder="Enter Email" />
	</div>
</div>
<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls">
	<label for="id_password">Password:</label><input class="form-control" id="id_password" name="password" type="password" placeholder="Enter Password" />
	</div>
</div>

<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls">
	<label for="id_first_name">First name:</label><input class="form-control" id="id_first_name" maxlength="128" name="first_name" type="text" placeholder="Enter First Name"  /><br />
	</div>
</div>

<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls"><label for="id_last_name">Last name:</label><input class="form-control" id="id_last_name" maxlength="128" name="last_name" type="text" placeholder="Enter Last Name"  /><br />
	</div>

</div>
	<div class="row control-group">
	<div class="form-group col-xs-12 floating-label-form-group controls"><label for="id_about_me">about me:</label><input class="form-control" id="id_about_me" maxlength="128" name="about_me" type="text" placeholder="About Me"  /><br />
	</div>
</div>

</div>
-->


     {{ user_form.as_p }}
            {{ profile_form.as_p }}
<br>
<br />
<div class="row">
	<div class="form-group col-xs-12">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
</div>


		</form>
	</div>
</div>
{%endif%}
{%endblock%}

templates/userpro/save.html
<!DOCTYPE html>
<html>
<head>
	<title>Rango</title>
</head>
<body>
	<h1> Register with Rango</h1>
	{% if registered %}
		Rango says: <strong> thank you </strong>
		<a href="/rango"> Return to Rango</a>
		{% else %}
		Rango says: <strong> Register here </strong>
		<form id="user_form" method = "post" action="/user/" enctype="multipart/form-data">
		{% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}

</body>
</html>

templates/userpro/useredit.html
{% extends "base.html" %}


{% block content%}


{% if edit %}
		<section>
		<div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Edit Complete</h2>
                    <br>
                    <a href="/"> Return to Home</a>
                </div>
            </div>
		
		</section>
		{% else %}
<div class ="container" style="padding-top:70px">
	<div class="row">
		<div class="col-lg-12 text-center">
			<h2 class="form-signin-heading">Edit Here</h2>
		</div>
	</div>
</div>
<hr/>
<div class="row container">
<div class="col-lg-8 col-lg-offset-2">
<form id="user_form" method = "post" action="/student/edit/" enctype="multipart/form-data">
{% csrf_token %}


{{profile_form.errors}}
	
<div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
	<textarea class="form-control" cols="40" id="id_about_me" name="about_me" placeholder="about me" required="false" rows="10">
</textarea>
	</div>
</div>
<br>

<div class="row">
	<div class="form-group col-xs-12">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
</div>


		</form>
	</div>
</div>
{%endif%}
{%endblock%}